(function($){var defaults={direction:'top',theme:'',position:{}};var settings;var margins={border:6,top:15,right:15,bottom:15,left:15}
var themes=['','pastelblue','lightgray','darkgray'];var positions=['top','top-right','right-top','right','right-bottom','bottom-right','bottom','bottom-left','left-bottom','left','left-top','top-left'];var titles=[];function getThemeName(element){for(var n=0;n<themes.length;n++){if(element.hasClass(themes[n]))return themes[n]};return settings.theme;}
function getTooltipPosition(element){for(var n=0;n<positions.length;n++){if(element.hasClass(positions[n]))return positions[n];};return settings.direction;}
function getTooltipTag(_event){var title_=titles[_event.data.index];if(title_.length>0)return('<div id="simple-tooltip-'+_event.data.index+'" class="simple-tooltip '+getTooltipPosition($(_event.target))+' '+getThemeName($(_event.target))+'">'+title_+'<span class="arrow"> </span></div>');return false;}
function mouseOver(_event){var element=$(this);var tooltip_tag=getTooltipTag(_event);if(tooltip_tag){var exist_=$('body').find('#simple-tooltip-'+_event.data.index);if(exist_.length>0){_event.preventDefault();return false;}
var temp_=$(tooltip_tag).appendTo($('body'));temp_.hide();reposTooltip(temp_,element);temp_.delay(180).fadeIn(200);}
_event.preventDefault();};function mouseOut(_event){var exist_=$('body').find('#simple-tooltip-'+_event.data.index);if(exist_.length==0){_debug('no existe el elemento: cancela');_event.preventDefault();return false;}
if(exist_.css('opacity')==0){_debug('opacidad 0: eliminarrrrrr');_event.preventDefault();exist_.remove();return false;}
exist_.clearQueue().stop().fadeOut(100,function(){exist_.remove()});};function reposTooltip(tooltip,element){var pos=element.offset();switch(getTooltipPosition(element)){default:case'top':pos.top-=parseInt(tooltip.outerHeight()+margins.top);pos.left+=parseInt((element.outerWidth()-tooltip.outerWidth())/2);break;case'top-right':pos.top-=parseInt(tooltip.outerHeight()+margins.bottom);pos.left+=parseInt(element.outerWidth()-margins.right-margins.border);break;case'right-top':pos.top-=parseInt(tooltip.outerHeight()-margins.bottom);pos.left+=parseInt(element.outerWidth()+margins.right);break;case'right':pos.top+=parseInt((element.outerHeight()-tooltip.outerHeight())/2);pos.left+=parseInt(element.outerWidth()+margins.right);break;case'right-bottom':pos.top+=parseInt(element.outerHeight()-margins.bottom);pos.left+=parseInt(element.outerWidth()+margins.right);break;case'bottom-right':pos.top+=parseInt(element.outerHeight()+margins.bottom);pos.left+=parseInt(element.outerWidth()-margins.right-margins.border);break;case'bottom':pos.top+=parseInt(element.outerHeight()+margins.bottom);pos.left+=parseInt((element.outerWidth()-tooltip.outerWidth())/2);break;case'bottom-left':pos.top+=parseInt(element.outerHeight()+margins.bottom);pos.left-=parseInt(tooltip.outerWidth()-margins.left-margins.border);break;case'left-bottom':pos.top+=parseInt(element.outerHeight()-margins.bottom);pos.left-=parseInt(tooltip.outerWidth()+margins.left);break;case'left':pos.top+=parseInt((element.outerHeight()-tooltip.outerHeight())/2);pos.left-=parseInt(tooltip.outerWidth()+margins.left);break;case'left-top':pos.top-=(tooltip.outerHeight()-margins.bottom);pos.left-=parseInt(tooltip.outerWidth()+margins.left);break;case'top-left':pos.top-=(tooltip.outerHeight()+margins.bottom);pos.left-=parseInt(tooltip.outerWidth()-margins.left);break;}
tooltip.css('top',pos.top);tooltip.css('left',pos.left);}
function addActions(){$('.simpletooltip').each(function(index,value){$(value).css('cursor','pointer');titles[index]=$(value).attr('title');$(value).attr('title','');$(value).bind('mouseenter',{index:index},mouseOver);$(value).bind('mouseleave',{index:index},mouseOut);})};function setSettings(settings_){settings=$.extend(defaults,settings_);};$.simpletooltip=function(settings_){setSettings(settings_);addActions();};})(jQuery);
var css = 'div.simple-tooltip{position:absolute;display:block;width:auto;max-width:280px;height:auto;padding:6px 8px;color:white;font:normal 1em/1em Helvetica,Arial,Sans-serif;border:solid 6px #00619e;background-color:#0083c0;line-height:15px;margin-bottom:30px;-webkit-box-shadow:0px 0px 10px rgba(0,0,0,0.2);-moz-box-shadow:0px 0px 10px rgba(0,0,0,0.2);box-shadow:0px 0px 10px rgba(0,0,0,0.2);border-radius:5px;-ms-border-radius:5px;-moz-border-radius:5px;-webkit-border-radius:5px;-khtml-border-radius:5px;z-index:2000}div.simple-tooltip span.arrow{display:block;position:absolute;width:17px;height:17px;background-image:url(./images/seablue-theme.png);background-repeat:no-repeat}div.simple-tooltip.pastelblue{background-color:#cddcf3;color:#444;border:solid 6px #fff;-webkit-box-shadow:0 0 12px rgba(0,0,0,.3);-moz-box-shadow:0 0 12px rgba(0,0,0,.3);box-shadow:0 0 12px rgba(0,0,0,.3)}div.simple-tooltip.pastelblue span.arrow{background-image:url(./images/pastelblue-theme.png)}div.simple-tooltip.lightgray{background-color:#dbdbdb;color:#444;border:solid 6px #b9b9b9;-webkit-box-shadow:0 0 12px rgba(0,0,0,.2);-moz-box-shadow:0 0 12px rgba(0,0,0,.2);box-shadow:0 0 12px rgba(0,0,0,.2)}div.simple-tooltip.lightgray span.arrow{background-image:url(./images/lightgray-theme.png)}div.simple-tooltip.darkgray{background-color:#505050;color:#eaeaea;border:solid 6px #303030;-webkit-box-shadow:0 0 10px rgba(0,0,0,.1);-moz-box-shadow:0 0 10px rgba(0,0,0,.1);box-shadow:0 0 10px rgba(0,0,0,.1)}div.simple-tooltip.darkgray span.arrow{background-image:url(./images/darkgray-theme.png)}div.simple-tooltip.top span.arrow{bottom:-23px;left:50%;margin-left:-8px;background-position:-102px 0}div.simple-tooltip.top-left span.arrow{bottom:-23px;right:2px;background-position:-85px 0}div.simple-tooltip.left-top span.arrow{bottom:2px;right:-23px;background-position:-68px 0}div.simple-tooltip.left span.arrow{top:50%;margin-top:-8px;right:-23px;background-position:-51px 0}div.simple-tooltip.left-bottom span.arrow{top:2px;right:-23px;background-position:-34px 0}div.simple-tooltip.bottom-left span.arrow{top:-23px;right:2px;background-position:-17px 0}div.simple-tooltip.bottom span.arrow{top:-23px;left:50%;margin-left:-8px;background-position:0 0}div.simple-tooltip.bottom-right span.arrow{top:-23px;left:2px;background-position:-187px 0}div.simple-tooltip.right-bottom span.arrow{top:2px;left:-23px;background-position:-170px 0}div.simple-tooltip.right span.arrow{top:50%;margin-top:-8px;left:-23px;background-position:-153px 0}div.simple-tooltip.right-top span.arrow{bottom:2px;left:-23px;background-position:-136px 0}div.simple-tooltip.top-right span.arrow{bottom:-23px;left:2px;background-position:-119px 0}div.simple-tooltip ul{font-size:12px;margin:5px}div.simple-tooltip li{font-size:12px}'
_OPT.load.evalcss(css);
delete css;
function jquery_tips_exec($selector)
{
	
	$.simpletooltip();
}